In [1]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

In [2]:
# open text file and read in data as `text`
with open('data/anna.txt', 'r') as f:
    text = f.read()

In [5]:
print(len(text))

1985223


In [6]:
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in text])

In [8]:
print(int2char)
print(char2int)

{0: '\n', 1: '8', 2: 'f', 3: '!', 4: 'd', 5: '5', 6: 'h', 7: 't', 8: 'n', 9: 'L', 10: '*', 11: 'Z', 12: ';', 13: ')', 14: 'r', 15: 'G', 16: '`', 17: 'Q', 18: 'P', 19: 'j', 20: 'u', 21: '6', 22: 'Y', 23: 'J', 24: '0', 25: 'M', 26: '(', 27: 'C', 28: 'O', 29: 'X', 30: 'K', 31: 'W', 32: 'v', 33: '/', 34: 'l', 35: '"', 36: 'N', 37: 'D', 38: '9', 39: 'V', 40: '_', 41: '%', 42: 'R', 43: 'c', 44: '-', 45: '.', 46: '@', 47: 'g', 48: ':', 49: 'A', 50: 'm', 51: 'E', 52: 'e', 53: 'i', 54: 'S', 55: 'q', 56: '?', 57: 'b', 58: 'o', 59: '$', 60: 's', 61: '3', 62: 'H', 63: 'I', 64: 'k', 65: 'B', 66: "'", 67: 'y', 68: 'z', 69: 'F', 70: '2', 71: '4', 72: ' ', 73: ',', 74: 'x', 75: '7', 76: '1', 77: 'w', 78: 'p', 79: 'T', 80: 'a', 81: 'U', 82: '&'}
{'\n': 0, '8': 1, 'f': 2, '!': 3, 'd': 4, '5': 5, 'h': 6, 't': 7, 'n': 8, 'L': 9, '*': 10, 'Z': 11, ';': 12, ')': 13, 'r': 14, 'G': 15, '`': 16, 'Q': 17, 'P': 18, 'j': 19, 'u': 20, '6': 21, 'Y': 22, 'J': 23, '0': 24, 'M': 25, '(': 26, 'C': 27, 'O': 28, 'X': 29,

In [10]:
print(encoded)
print(len(encoded))

[27  6 80 ... 60 45  0]
1985223


In [11]:

def one_hot_encode(arr, n_labels):
    
    # Initialize the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [12]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


In [13]:
def get_batches(arr, batch_size, seq_length):
    '''Create a generator that returns batches of size
       batch_size x seq_length from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       seq_length: Number of encoded chars in a sequence
    '''
    
    ## TODO: Get the number of batches we can make
    n_batches = 
    
    ## TODO: Keep only enough characters to make full batches
    arr = 
    
    ## TODO: Reshape into batch_size rows
    arr = 
    
    ## TODO: Iterate over the batches using a window of size seq_length
    for n in range(0, arr.shape[1], seq_length):
        # The features
        x = 
        # The targets, shifted by one
        y = 
        yield x, y


SyntaxError: invalid syntax (<ipython-input-13-099b0f3d87f5>, line 13)