In [2]:
import torch

In [3]:
def activation(x):
    return 1 / (1 + torch.exp(-x))

In [4]:
torch.manual_seed(7)
features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

print(features)
print(weights)
print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [5]:
activation(torch.mm(features, weights.view(5, 1)) + bias)

tensor([[0.1595]])

In [6]:
print(activation(torch.sum(features * weights) + bias))

tensor([[0.1595]])


In [29]:

### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [30]:
h1 = activation(torch.mm(features, W1) + B1)
print(h1)

tensor([[1., 1.]])


In [31]:
output = activation(torch.mm(h1, W2) + B2)

print(output)

tensor([[0.4311]])


In [28]:
import numpy as np

a = np.random.rand(4, 5)

b = torch.from_numpy(a)
b.numpy()


array([[0.84387275, 0.6349693 , 0.6400407 , 0.80619921, 0.37323919],
       [0.22330154, 0.38327614, 0.07459771, 0.63385966, 0.94971373],
       [0.42666233, 0.11742236, 0.52070229, 0.02848353, 0.24793483],
       [0.96467989, 0.83651911, 0.97103089, 0.08027883, 0.830673  ]])